### PR TITLE
noexcept function c++17 hotfix

### PR DESCRIPTION
**Pull request by rohlem**
This PR extends the template trait struct system for functions in meta and meta_detail (basic_traits and member_function_wrapper) to fix noexcept functions in C++17. Comes with two test cases (one for usertypes, just in case).

I assume you have some greater plan moving to C++17, and there might be some more improvements in some other areas, but in my usage of Sol this is the only thing that ever came up and it looked easy to do, so here it is. All changes are hidden behing preprocessor if-s with the correct feature-testing macro, so there should be no regressions (or at all notable change really) in any C++14 builds.

(old info, now commit 3 is removed: Additionally, the last commit changes 3 places in which the tests and examples use the return type conversion to string mentioned in issue #414 , just to make it actually buildable (on my setup, mingw-g++ 7.1.0). Feel free to omit that commit (or tell me to remove it, if that's easier) if you'd prefer dealing with those spots yourself.)

### CODE REVIEW

**Comment by ThePhD** [comment]
The code here is g++/clang++ specific and does not consider VC++. I will need to vet this code and everything about it before accepting a PR.

**Comment by rohlem** [comment]
The very last commit is a fix for g++ and clang++s current C++17 behaviour, it sacrifices the readability of the example and test code but otherwise cannot lead to any regressions of anything. If you don't want it I'll gladly remove it from this PR, I just thought it helps to be able to build it (otherwise C++17 builds are broken in g++ and clang++).

The preprocessor-ifs are SD-6 Feature Test macros according to [gcc's documentation](https://gcc.gnu.org/projects/cxx-status.html) , so they come from standards people and we'd hope that implementers correctly specify them.
Undefined macros evaluate to 0 iirc, so the ifs lead to false and there is no change to behaviour.
If you want more thorough/distinct testing a different macro in some compatibility header file would be the way to go (right?) and this standardized constant is a good way to start.
Either way, compliant C++14 behaviour is unaffected.

**Comment by rohlem** [comment]
ok, scratch that last commit, all the build bots (none of which use gcc 7) fail with explicit static_casts. I cannot understand how an implicit conversion changes any of that, but I'll remove that commit from this PR immediately, since it's clearly not working out.

**Comment by Nava2** [comment]
@ThePhD have you considered [AppVeyor](https://www.appveyor.com/docs/build-environment/#visual-studio-2017) as they have VS 2017 support?

**Comment by ThePhD** [comment]
@Nava2 I have, but I just haven't had the time to get to do it. I was planning to do it when I started adding test harnesses for g++ 5, 6, and 7 | clang++ 3.7, 3.8, 3.9 and 4.0 while putting all the older ones is "allowed failures" buckets. I also wanted to look into getting more updated OSX images on travis-ci so I could finally see if I could get `std::tuple`'s compiler bug that's been plaguing builds from old XCode images to be corrected...

That's going to take a while though.

**Comment by ThePhD** [comment]
A quick check to the VS2017 feature table reveals that `noexcept` is not part of the type system just yet: https://blogs.msdn.microsoft.com/vcblog/2017/05/10/c17-features-in-vs-2017-3/

**Comment by rohlem** [comment]
(I'm so sorry it took me so long to respond, I thought I'd get to it sooner.)
Thanks for taking it into your own hands, and happy to see there's potential for improvements in a lot of places; I hope I didn't slow you down too much. Keep it up! ^^

**Pull request merged**
