### PR TITLE
Don't use <lua.hpp>

### PR DESCRIPTION
**Pull request by Cannedfood**
The <lua.hpp> header is not included in some lua distributions, in particular www.github.com/lua/lua.

### CODE REVIEW

**Comment by ThePhD** [comment]
Counterpoint: they should have `lua.hpp` and you should petition them to add it.

**Comment by ThePhD** [comment]
... In fact, it was supposed to be part of that distribution. Did they remove it??

**Comment by ThePhD** [comment]
Oh, it's part of the official distribution, just not that mirror. And to be quite honest, I'm not sure that repo is for anything other than visible history.

I'd rather not.

**Comment by Cannedfood** [comment]
According [mailing list](http://lua-users.org/lists/lua-l/2004-09/msg00559.html) they won't add it. 
And it is somewhat annoying/ugly to work around it if you're using the git mirror.

**Comment by ThePhD** [comment]
This has hooks for detection in sol3, but I'm not really interested in porting this to sol2: https://github.com/ThePhD/sol2/blob/sol3/include/sol/compatibility/version.hpp#L40

**Pull request closed without merging**
